apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "arbeidssokerregistrering-demo"
  namespace: "paw"
  labels:
    "team": "paw"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/arbeid/registrering/api/isalive"
    initialDelay: 3
  readiness:
    path: "/arbeid/registrering/api/isready"
    initialDelay: 3
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: SELF_URL
      value: https://arbeid.ekstern.dev.nav.no/arbeid/registrering
    - name: DEKORATOR_URL
      value: https://dekoratoren.ekstern.dev.nav.no/
    - name: DEKORATOR_ENV
      value: dev
    - name: NEXT_PUBLIC_SELF_URL
      value: https://arbeid.ekstern.dev.nav.no/arbeid/registrering
    - name: NEXT_PUBLIC_START_URL
      value: https://arbeid.ekstern.dev.nav.no/arbeid/registrering/start
    - name: NEXT_PUBLIC_AMPLITUDE_API_KEY
      value: 9845ded64c69cd068651cd0d968e0796
    - name: NEXT_PUBLIC_AMPLITUDE_ENDPOINT
      value: https://amplitude.nav.no/collect
    - name: NEXT_PUBLIC_ENABLE_MOCK
      value: enabled
    - name: NEXT_PUBLIC_DITTNAV_URL
      value: https://www.nav.no/minside
    - name: NEXT_PUBLIC_DAGPENGESOKNAD_URL
      value: https://www.nav.no/dagpenger/dialog/soknad
    - name: NEXT_PUBLIC_DIALOG_URL
      value: https://www.nav.no/arbeid/dialog
    - name: PAM_JANZZ_URL
      value: https://arbeidsplassen.nav.no/pam-janzz/rest
    - name: SISTEARBEIDSFORHOLD_FRA_AAREG_URL
      value: https://arbeid.ekstern.dev.nav.no/arbeid/registrering/api/mocks/arbeidsforhold-fra-aareg
    - name: KONTAKTINFORMASJON_URL
      value: https://arbeid.ekstern.dev.nav.no/arbeid/registrering/api/mocks/kontaktinformasjon
    - name: FEATURE_TOGGLE_URL
      value: https://arbeid.ekstern.dev.nav.no/arbeid/registrering/api/mocks/features
    - name: NODE_ENV
      value: development
  ingresses:
    - https://arbeid.ekstern.dev.nav.no/arbeid/registrering
    - https://arbeid.ansatt.dev.nav.no/arbeid/registrering
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: arbeidsplassen.nav.no
        - host: arbeid.ekstern.dev.nav.no
        - host: paw-unleash-api.nav.cloud.nais.io
