apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "arbeidssokerregistrering"
  namespace: "paw"
  labels:
    "team": "paw"
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  image: {{image}}
  port: 3000
  liveness:
    path: "/arbeid/registrering/api/isalive"
    initialDelay: 3
  readiness:
    path: "/arbeid/registrering/api/isready"
    initialDelay: 3
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /arbeid/registrering
    - name: DEKORATOR_ENV
      value: prod
    - name: NEXT_PUBLIC_SELF_URL
      value: https://www.nav.no/arbeid/registrering
    - name: NEXT_PUBLIC_START_URL
      value: https://www.nav.no/arbeid/registrering/start
    - name: NEXT_PUBLIC_AMPLITUDE_API_KEY
      value: 913768927b84cde5eac0d0d18c737561
    - name: NEXT_PUBLIC_AMPLITUDE_ENDPOINT
      value: https://amplitude.nav.no/collect
    - name: NEXT_PUBLIC_ENABLE_MOCK
      value: disabled
    - name: NEXT_PUBLIC_DITTNAV_URL
      value: https://www.nav.no/minside
    - name: NEXT_PUBLIC_ARBEIDSSOEKERREGISTERET_URL
      value: https://www.nav.no/arbeidssoekerregisteret
    - name: NEXT_PUBLIC_DAGPENGESOKNAD_URL
      value: https://www.nav.no/dagpenger/dialog/soknad
    - name: NEXT_PUBLIC_BRUKERDIALOG_DAGPENGER_URL
      value: https://brukerdialog-dagpenger.nav.no
    - name: NEXT_PUBLIC_DIALOG_URL
      value: https://www.nav.no/arbeid/dialog
    - name: PAM_ONTOLOGI_URL
      value: http://pam-ontologi.teampam/rest
    - name: NODE_ENV
      value: production
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
    - name: OPPGAVE_API_URL
      value: http://aia-backend/aia-backend/oppgave
    - name: NEXT_PUBLIC_ASSET_PREFIX
      value: https://cdn.nav.no/paw/arbeidssokerregistrering
    - name: AAREG_REST_API
      value: https://aareg-services.prod-fss-pub.nais.io/api
    - name: AAREG_CLUSTER
      value: prod-fss
    - name: AAREG_APPNAME
      value: aareg-services-nais
    - name: INNGANG_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: ARBEIDSSOKERREGISTERET_OPPSLAG_API_V2_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag-v2
    - name: FORSIDE_URL
      value: https://www.nav.no/registrer-arbeidssoker
  envFrom:
     - secret: poa-arbeidssokerregistrering-unleash-api-token
  ingresses:
    - https://www.nav.no/arbeid/registrering
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: true
      autoLoginIgnorePaths:
        - /arbeid/registrering/api/isalive
        - /arbeid/registrering/api/isready
        - /arbeid/registrering/
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: paw-unleash-api.nav.cloud.nais.io
        - host: aareg-services.prod-fss-pub.nais.io
      rules:
        - application: paw-arbeidssokerregisteret-api-inngang
        - application: paw-arbeidssoekerregisteret-api-oppslag
        - application: paw-arbeidssoekerregisteret-api-oppslag-v2
        - application: aia-backend
        - application: nav-dekoratoren
          namespace: personbruker
        - application: pam-ontologi
          namespace: teampam
        - application: aareg-services-nais
          namespace: arbeidsforhold
          cluster: prod-fss
