apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "arbeidssokerregistrering"
  namespace: "paw"
  labels:
    "team": "paw"
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  image: {{image}}
  port: 3000
  liveness:
    path: "/arbeid/registrering/api/isalive"
    initialDelay: 3
  readiness:
    path: "/arbeid/registrering/api/isready"
    initialDelay: 3
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: SELF_URL
      value: https://arbeid.intern.dev.nav.no/arbeid/registrering
    - name: DEKORATOR_URL
      value: https://dekoratoren.ekstern.dev.nav.no/
    - name: DEKORATOR_ENV
      value: dev
    - name: NEXT_PUBLIC_SELF_URL
      value: https://arbeid.intern.dev.nav.no/arbeid/registrering
    - name: NEXT_PUBLIC_START_URL
      value: https://arbeid.intern.dev.nav.no/arbeid/registrering/start
    - name: NEXT_PUBLIC_AMPLITUDE_API_KEY
      value: 9845ded64c69cd068651cd0d968e0796
    - name: NEXT_PUBLIC_AMPLITUDE_ENDPOINT
      value: https://amplitude.nav.no/collect
    - name: NEXT_PUBLIC_ENABLE_MOCK
      value: disabled
    - name: NEXT_PUBLIC_DITTNAV_URL
      value: https://www.intern.dev.nav.no/minside
    - name: NEXT_PUBLIC_DAGPENGESOKNAD_URL
      value: https://arbeid.intern.dev.nav.no/dagpenger/dialog/soknad
    - name: NEXT_PUBLIC_DIALOG_URL
      value: https://www.dev.nav.no/arbeid/dialog
    - name: PAM_JANZZ_URL
      value: https://arbeidsplassen.nav.no/pam-janzz/rest
    - name: NODE_ENV
      value: test
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
    - name: OPPGAVE_API_URL
      value: http://aia-backend/aia-backend/oppgave
    - name: NEXT_PUBLIC_ASSET_PREFIX
      value: https://cdn.nav.no/paw/arbeidssokerregistrering
    - name: AAREG_REST_API
      value: https://aareg-services-q1.dev-fss-pub.nais.io/api
    - name: AAREG_CLUSTER
      value: dev-fss
    - name: AAREG_APPNAME
      value: aareg-services-nais-q1
    - name: INNGANG_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: OPPDATER_OPPLYSNINGER_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
    - name: ARBEIDSSOKERREGISTERET_OPPSLAG_API_URL
      value: http://paw-arbeidssoekerregisteret-api-oppslag
  envFrom:
    - secret: poa-arbeidssokerregistrering-unleash-api-token
  ingresses:
    - https://arbeid.intern.dev.nav.no/arbeid/registrering
    - https://arbeid.ansatt.dev.nav.no/arbeid/registrering
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: arbeidsplassen.nav.no
        - host: paw-unleash-api.nav.cloud.nais.io
        - host: aareg-services-q1.dev-fss-pub.nais.io
      rules:
        - application: paw-arbeidssokerregisteret-api-inngang
        - application: paw-arbeidssoekerregisteret-api-oppslag
        - application: veilarbregistrering
        - application: aia-backend
        - application: nav-dekoratoren
          namespace: personbruker
        - application: aareg-services-nais-q1
          namespace: arbeidsforhold
          cluster: dev-fss
